ErrorDoc = require "error-doc"
module.exports = Errors = ErrorDoc.create()
    .define("PermissionDenied")
    .define("AuthorizationFailed")
    .define("NetworkError")
    .define("Timeout")
    .define("InvalidCaptcha")
    .define("InvalidSource")
    .define("InvalidAction")
    .define("NotExists")
    .define("UnkownError")
    .define("ParseError")
    .define("LogicError")
    .define("Duplication")
    .generate()

