module.exports = Leaf.ErrorDoc.create()
    .define("UnknownError")
    .define("Abort")
    .define("NetworkError")
    .define("ProgrammerError")
    .define("ProgrammerError:LogicError")
    .generate()
