tm = new Leaf.TemplateManager()
module.exports = tm
if window.location.toString().indexOf("?debug")>0
    tm.enableCache = false
else
    tm.enableCache = true
tm.use "archive-list"
        ,"archive-list-item"
        ,"source-list"
        ,"source-list-folder"
        ,"source-list-item"
        ,"add-source-popup"
        ,"read-later-list"
        ,"read-later-list-item"
        ,"tag-list"
        ,"tag-list-item"
        ,"tag-archive-list"
        ,"custom-source-list"
        ,"custom-archive-list"
        ,"custom-group-item"
        ,"custom-source-item"
        ,"custom-tag-item"
        ,"tag-selector"
        ,"source-selector"
        ,"context-menu"
        ,"context-menu-item"
        ,"archive-filter"
        ,"archive-filter-condition"
        ,"search-list"
        ,"search-list-item"
        ,"archive-displayer"
        ,"archive-displayer-list-selector"
        ,"list-view-list"
        ,"list-view-list-item"
        ,"list-view-archive-list"
        ,"list-view-archive-list-item"
        ,"p2p-node-item"
        ,"p2p-node-list-item"
        ,"p2p-list"
        ,"p2p-node-info-displayer"
        ,"source-detail"
        ,"int-entry"
        ,"string-entry"